aws/amazon-cloudwatch-agent-test

- test/metric/metric_value_query.go
- test/metric/net.go
- test/metric/query-json.json
- test/metric_value_benchmark/agent_configs/net_config.json
- test/metric_value_benchmark/metrics_value_benchmark_test.go
- test/metric_value_benchmark/net_test.go
Add E2E Sanity Test for Net 
* Added integration test to validate that the agent publishes metrics for the Net input plugin
Ran on my fork: https://github.com/khanhntd/amazon-cloudwatch-agent/actions/runs/3437608790/jobs/5732904202
```
null_resource.integration_test (remote-exec): 2022/11/10 14:59:57 ==============Net==============
null_resource.integration_test (remote-exec): 2022/11/10 14:59:57 ==============Successful==============
null_resource.integration_test (remote-exec): net_bytes_sent     Successful
null_resource.integration_test (remote-exec): net_bytes_recv     Successful
null_resource.integration_test (remote-exec): net_drop_in …
```
> Add E2E Sanity Test For Net

- generator/test_case_generator.go
- test/agent_util.go
- test/collection_interval/collection_interval_test.go
- test/collection_interval/resources/agent_interval_10s.json
- test/collection_interval/resources/default.json
- test/collection_interval/resources/metric_interval_10s.json
- test/collection_interval/resources/metric_override_interval_10s.json
- test/cwm_util.go
- test/run_as_user/run_as_user_test.go
- test/util.go
No collection interval test
Add collection interval test
go test ./test/collection_interval -p 1 -timeout 30m -v
These tests can run on mac. We now split out the integration tests out of the main repo. We do not need tags to prevent the test running as a unit test.
> Add Collection Interval Test And Let It Work On Darwin

- msi/tools/amazon-cloudwatch-agent.wxs
see title
add properties to WXS file.
- Manually build MSI and verify the options are not visible in "control panel" or "settings".
> Disable modify and repair operations to avoid non-admin being able to run them. This is commonly practice. The options are not useful for users.

- test/metric/metric_value_query.go
- test/metric/swap.go
- test/metric_value_benchmark/agent_configs/netstat_config.json
- test/metric_value_benchmark/agent_configs/swap_config.json
- test/metric_value_benchmark/metrics_value_benchmark_test.go
- test/metric_value_benchmark/swap_test.go
E2E sanity test for NetStat
[Ran on hacked_ec2 branch of fork](https://github.com/williazz/amazon-cloudwatch-agent/actions/runs/3759997774/jobs/6390558972)
```
null_resource.integration_test (remote-exec): 2022/12/20 19:45:32 >>>>>>>>>>>>>>Successful<<<<<<<<<<<<<<
null_resource.integration_test (remote-exec): 2022/12/20 19:45:32 ==============NetStat==============
null_resource.integration_test (remote-exec): 2022/12/20 19:45:32 ==============Successful==============
null_resource.integration_test (remote-exec): netstat_tcp_close         Successful
null_resource.integration_test (remote-exec): netstat_tcp_close_wait    Successful …
```
> Add E2E sanity test for NetStat

- terraform/ec2/linux/main.tf
Tryign to connect using ec2-user on ubuntu instances. 
Use user var for ssh connection.
Failed tests https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/3857573617/jobs/6609866529
> Use User Var For EFS SSH Connect

- terraform/ec2/linux/install-efs-utils.sh
Failed test for efs on rhel8 and ol9
Follow https://github.com/aws/efs-utils guide for yum
Failed test https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/3877393955/jobs/6612416155
> Fix EFS Utils Install On Rhel8 And OL9

- terraform/ec2/localstack/variables.tf
Reduce cpu usage of ec2 instances. 
Local stack now uses t3a medium instead of large. 
None
> Reduce CPU Usage Localstack

- test/metric/dimension/container_insights_provider.go
- test/metric/dimension/custom_provider.go
- test/metric/dimension/host_provider.go
- test/metric/dimension/instanceid_provider.go
- test/metric/dimension/provider.go
- test/metric_append_dimension/no_append_dimensions_test.go
- test/metric_value_benchmark/disk_test.go
```
[ec2-user@ip-172-31-45-254 amazon-cloudwatch-agent-test-fix-tests]$ go test ./test/metric_append_dimension/ -p 1 -timeout 1h -computeType=EC2 -v
=== RUN   TestMetricsAppendDimensionTestSuite
>>>> Starting MetricAppendDimensionTestSuite
=== RUN   TestMetricsAppendDimensionTestSuite/TestAllInSuite
2023/01/18 22:37:10 Running NoAppendDimension
2023/01/18 22:37:10 Starting agent using agent config file agent_configs/no_append_dimension.json
2023/01/18 22:37:10 Copy File agent_configs/no_append_dimension.json to /opt/aws/amazon-cloudwatch-agent/bin/config.json
2023/01/18 22:37:10 File agent_configs/no_append_dimension.json abs path /home/ec2-user/amazon-cloudwatch-agent-test-fix-tests/test/metric_append_dimension/agent_configs/no_append_dimension.json
2023/01/18 22:37:10 File : …
```
> Fix Append Dimension Test

- test/metric_value_benchmark/agent_configs/prometheus_config.json
- test/metric_value_benchmark/prometheus_test.go
This PR addresses two issues that were highlighted when running the prometheus test on our staging repo (the test was working fine on our public repo).
1. Summary metrics need some additional work for CCWA to behave the same as CWA. Hence the current assertions will fail for CCWA.
2. `prom_metric_type` is auto-added as a label/dimension by `awsemfexporter` but it is not considered as a valid dimension when doing the dimension filtering. Hence if someone uses `prom_metric_type` as a dimension filter in their config, it currently wont work. This is a very rare usecase but this test does happen to do it. 
1. We have a backlog item to track this. So until then, commenting out the checks for summary metrics.
2. I'll create a backlog item to track the fix but tweaking the test for now to NOT …
> Do not use prom_metric_type and comment out summary checks for prometheus

- internal/common/agent_util_unix.go
- test/cloudwatchlogs/publish_logs_test.go
- test/cloudwatchlogs/resources/config_log.json
- test/cloudwatchlogs/resources/config_log_filter.json
- test/cloudwatchlogs/resources/config_log_rotated.json
- test/metric_value_benchmark/ecs_daemon_base_test_runner.go
Agent cannot read and publish the log file before it is being deleted. 
```
null_resource.integration_test (remote-exec):     cloudwatchlogs.go:72: Error occurred while getting log events: operation error CloudWatch Logs: GetLogEvents, https response error StatusCode: 400, RequestID: def1a3b4-b01c-414d-9199-b73c64261009, ResourceNotFoundException: The specified log group does not exist.
null_resource.integration_test (remote-exec): === RUN   TestWriteLogsToCloudWatch/Client-side_log_filtering
null_resource.integration_test (remote-exec): 2023/01/19 23:36:58 Copy File resources/config_log_filter.json to /opt/aws/amazon-cloudwatch-agent/bin/config.json
null_resource.integration_test (remote-exec): 2023/01/19 23:36:58 File resources/config_log_filter.json abs path …
```
> Fix Cloud Watch Logs Test

- test/metric_value_benchmark/metrics_value_benchmark_test.go
Tests currently fail in private repo workflow E2E tests.
Disable them temporarily. We have backlog items to work on them and need to reenable this after.
> Disable statsd, emf and collectd tests since they arent supported by CCWA yet

- terraform/ec2/linux/main.tf
```
│ Error: Argument or block definition required
│ 
│   on main.tf line 29, in locals:
│   29:     : "${var.s3_bucket}/integration-test/binary/${var.cwa_github_sha}/linux/${var.arc}/${var.binary_name}"
│ 
│ An argument or block definition is required here.
```
Put the binary expression all on one line
N/A
> Fix Canary Terraform Syntax

- environment/MetaData.go
- terraform/ec2/linux/main.tf
- test/ca_bundle/ca_bundle_test.go
- test/ca_bundle/resources/integration/ssl/with/combine/bundle/common-config.toml
- test/ca_bundle/resources/integration/ssl/with/original/bundle/common-config.toml
- test/ca_bundle/resources/integration/ssl/without/bundle/common-config.toml
- test/ca_bundle/resources/integration/ssl/without/bundle/http/common-config.toml
Ca bundle config is only required for ca bundle test.
Move CA Bundle Localstack Config Into Test Instead Of Terraform EC2
go test ./test/ca_bundle/ -p 1 -timeout 1h -computeType=EC2 -bucket=private-cloudwatch-agent-integration-test -cwaCommitSha=adbf82d787639641ddabf969e6c119072efc71a3 -caCertPath=/etc/ssl/certs/ca-bundle.crt -v
> CA Bundle Localstack Config In Test Instead Of Terraform EC2

- test/ca_bundle/ca_bundle_test.go
- test/ca_bundle/resources/integration/ssl/with/combine/bundle/config.json
Ca bundle test is failing due to wrong configuration. 
Fix config and add more logging
https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/4127740089/jobs/7131675206
> Fix Localstack Config File

- test/metric/dimension/provider.go
- test/metric/metric_value_query.go
- test/metric_dimension/agent_configs/aggregation_dimensions.json
- test/metric_dimension/aggregate_dimension_test.go
- test/metric_dimension/aggregation_dimensions_test.go
- test/metric_dimension/metrics_dimension_test.go
- test/metric_value_benchmark/cpu_test.go
Currently there is a test which just tests the `"aggregation_dimensions"` option with a single roll up like this:
```
{
"agent": {
"metrics_collection_interval": 15,
"run_as_user": "root",
"debug": true,
"logfile": ""
},
"metrics": {
"namespace": "MetricAggregateDimensionTest",
"append_dimensions": {
"InstanceId": "${aws:InstanceId}",
"InstanceType": "${aws:InstanceType}"
},
"aggregation_dimensions": [[]],
"metrics_collected": {
"cpu": {
"measurement": [
"time_active", "time_guest"
]
}
},
"force_flush_interval": 5
}
}
```
This is not sufficient test coverage.
We should test multiple aggregations.
And we should verify negative cases such as aggregating on a dimension that does not exist does not cause any issue with other aggregations.
And that CWA doesn't do any extra aggregations which …
> Improve "aggregation_dimensions" testing

- terraform/setup/vpc.tf
Can't connect to localstack since port is not open. 
Open port for localstack
https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/4197203954/jobs/7279213162
> Allow TCP From 4566 So We Can Connect To Localstack

- terraform/ecs_ec2/daemon/main.tf
Set IMDSv2 with hop limit 2 in Container Environment since the [hop limit required for container is 2](https://docs.amazonaws.cn/en_us/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations); however, the default hop limit being set for cluster is 1. Therefore, changing it to 2 to fix our ECS EC2
```
To avoid the process of falling back to IMDSv1 and the resultant delay, in a container environment we recommend that you set the hop limit to 2
```
I [have run with my forked](https://docs.amazonaws.cn/en_us/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html)
> Set IMDSv2 with hop limit 2 in Container Environment

- generator/resources/ec2_linux_test_matrix.json
Need to test debian 11 platform.  
Add debian 11 arm as test. 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4246127488
Failures are due to too many mount targets in account. Working on a fix now.
> Add Debian ARM11 Tests

- internal/common/metrics.go
- test/metric/metric_value_query.go
- test/metric_value_benchmark/agent_configs/statsd_config.json
- test/metric_value_benchmark/metrics_value_benchmark_test.go
- test/metric_value_benchmark/statsd_test.go
Current statsd test is disabled.
It also relies on a specific bash script existing (part of a custom AMI).
I am re-enabling this test and reducing the need to run this test on a special AMI.
Now developers can run this test on any EC2 instance which has:
1. CWA installed
2. Go installed
3. This code repository checked out.
Generate statsd metrics from a goroutine instead of relying on a bash script built into the AMI.
- `make compile`
- From an AL2 EC2 instance, `go test -v -p=1 -count=1 -timeout=60m ./test/metric_value_benchmark/ -computeType=EC2`:
```
[ec2-user@ip-172-31-17-153 amazon-cloudwatch-agent-test]$ go test -failfast -p=1 -count=1 -v …
```
> Enable statsd test and improve it.

- generator/resources/ec2_performance_test_matrix.json
- go.mod
- go.sum
- internal/awsservice/dynamodb.go
- internal/common/metrics.go
- test/performance/logs/parameters.yml
- test/stress/statsd/parameters.yml
- validator/validators/performance/performance_models.go
- validator/validators/performance/performance_stats.go
- validator/validators/performance/performance_validator.go
Continue as part of onboarding metrics load to [performance validator test](https://github.com/aws/amazon-cloudwatch-agent-test/pull/151). As discussed in the previous PR,  there are three stages when starting the validator:
* [GenerateLoad](https://github.com/aws/amazon-cloudwatch-agent-test/blob/main/validator/models/validator_factory.go#L10): Sending the load to CloudWatchAgent
* [CheckData](https://github.com/aws/amazon-cloudwatch-agent-test/blob/main/validator/models/validator_factory.go#L11) : To get metrics defined [by the yaml and validate the metrics](https://github.com/aws/amazon-cloudwatch-agent-test/compare/main...khanhntd:amazon-cloudwatch-agent-test:add_performance?expand=1#diff-4182821602cec8db84c8b29427a65c5a63beff4c19bcf93e305966bed05a721eR20-R72)
* …
> Send metrics to database after query performance metrics from CWA

- generator/resources/ec2_mac_test_matrix.json
│ Error: creating EC2 Instance: InvalidParameterValue: The architecture 'x86_64_mac' of the specified instance type does not match the architecture 'arm64_mac' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
Fix the issue by matching arc to instance tpye
None
> Arm64 Mac Needs To Use mac2.metal

- terraform/ec2/mac/main.tf
No validator to download because bad path
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4896157980/jobs/8742742893
Fix download validator path
None
> Fix Validator Download Path

- terraform/ec2/linux/main.tf
Canary tests have the same naming scheme as other regular integration tests which can make it hard to distinguish the instances being generated. This also causes issue if daily resource cleanup code terminates all integration tests on a daily basis which will also terminate canary at the same time.
Change the name of canary tests instance name with the pattern of `cwagent-canary-test-ec2-${var.test_name}-${module.common.testing_id}`
Verified on personal account that the instances have been created correctly based on the new naming pattern.
> Use new name tag for canary test

- test/soak/soak_test.go
Integration tests get called with `-computeType=` flag.
But the soak test will fail like so:
```
[ec2-user@ip-172-31-17-153 amazon-cloudwatch-agent-test]$ go test ./test/soak -run TestSoakHigh -p 1 -timeout 1h -computeType=EC2
flag provided but not defined: -computeType
Usage of /tmp/go-build1947034016/b001/soak.test:
```
This test was missing some flag parsing code that all the other tests have.
Added this missing flag parsing.
- Manual ran test on AL2 and it passed:
```
[ec2-user@ip-172-31-17-153 amazon-cloudwatch-agent-test]$ go test ./test/soak -run TestSoakHigh -p 1 -timeout 1h -computeType=EC2
go: downloading …
```
> Fix soak test unrecognized flag.

- cmd/emf-generator/emf-generator.go
- cmd/log-generator/log-generator.go
- cmd/statsd-generator/statsd-generator.go
- test/soak/soak_test.go
The soak test is a short test that just starts the agent and some background generator programs.
The generator programs run indefinitely.
The intention was that the Terraform code would run a bash sleep command followed by a shutdown which would cause the EC2 instance to terminate. While that is still possible, I also think it is a good idea to allow users to control how long the generators run.
Considered using a channel and having all goroutines check the channel.
Simpler than that is just sleeping the desired amount of time and then exiting.
There is no clean up to worry about.
- Manual testing:
- `go run ./cmd/statsd-generator -runTime=15s …
> Default soak time

- msi/tools/create_msi.ps1
- pkg/tools/create_pkg.sh
nightly build, nonprod release, and prod release will want to create Mac and Windows packages at alternate S3 bucket paths.
Change build scripts
- none
> Mac and windows release

- generator/test_case_generator.go
- restart integ test is missing for Windows
- Add missing test back
> add missing restart test for windows

- test/metric/metric_value_query.go
- test/metric_value_benchmark/agent_configs/prometheus.yaml
- test/metric_value_benchmark/prometheus_test.go
The prometheus test is failing due to bugs that were recently introduced.
* We reduced the metric collection interval so the tests are quicker but the same was not reflected in the prometheus scrape interval, hence not giving it enough time.
* We seem to setup the agent config twice and duplicate code so this cleans that up as well.
* The summary tests that were commented are now expected to work (since we no longer use upstream prometheus_receiver)
* Reduce prometheus scrape interval
* Cleanup duplicated code
* Uncomment summary tests
* Passing prometheus test: https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/5236695480/j …
> Fix prometheus test bugs

- generator/resources/ec2_userdata_test_matrix.json
There was a bad merge where the userdate test matrix was removed and now causing it to fail on the integration test. 
```
Error when evaluating 'strategy' for job 'EC2UserDataIntegrationTest'. .github/workflows/integration-test.yml (Line: 652, Col: 17): Error parsing fromJson,.github/workflows/integration-test.yml (Line: 652, Col: 17): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/integration-test.yml (Line: 652, Col: 17): Unexpected value ''
```
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5248142140
Adding back the test matrix will allow the integration test to retrieve proper information for it to execute the userdata test.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Add back userdata test matrix for generation

- generator/test_case_generator.go
- terraform/ec2/win/variable.tf
- terraform/validator/main.tf
- test/performance/system/agent_config.json
Bugs were introduced over past commits that break the performance tests.
* Update test dir paths for win, mac & validator. The validator should not use contextual paths since it can be imported at any level by diff plugnins. For example, mac & win are nested 3 levels deep but performance is nested 2 levels deep. And given they both source in the validator, it cant have relative paths.
* Remove unsuppported `metrics_collection_interval` for ethtool.
* Run with passing performance/system tests: https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/5280181528
* WIP to test win, mac and other performance tests
> Performance test bug fixes

- terraform/stress/amis.tf
- terraform/stress/iam.tf
- terraform/stress/main.tf
- terraform/stress/providers.tf
- terraform/stress/sshkey.tf
- terraform/stress/variables.tf
- terraform/stress/vpc.tf
We are currently missing the terraform setup for stress tests.
Add the terraform setup for stress tests (mostly structured similarly to the existing performance tf setup)
* Test run showing passing stress tests (https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5316367723)
* [Sidenote] The failing performance tests in the run above are expected and will be fixed with https://github.com/aws/amazon-cloudwatch-agent-test/pull/262
> Terraform setup for stress tests

- generator/resources/ec2_linux_test_matrix.json
- internal/common/agent_util_unix.go
integration tests were failing for SUSE specifically
1. SUSE CA certs are located in a different place than the other flavors of Linux which is why we were failing the initial part of reading the cert file to create a PEM.
2. Calling `journalctl` in SUSE requires sudo permissions
I found the right path for the CA cert by running:
```bash
sh-4.4$ rpm -ql ca-certificates-2+git20210309.21162a6-2.1.noarch | grep ca-bundle
/etc/ssl/ca-bundle.pem
/var/lib/ca-certificates/ca-bundle.pem
```
Running `ls -al /etc/ssl` shows that the file there is a symlink to the one under `/var/lib`, but to keep it somewhat consistent with the other test configurations I used the one under `/etc/ssl`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Fix CA cert test for SUSE Linux

- terraform/ec2/win/main.tf
Some windows tests are failing due to existing SSM parameter name
Append test id to parameter name to avoid a collision
> add test id to ssm param name to avoid collision

- terraform/ec2/linux/main.tf
- terraform/ec2/linux/variables.tf
Need to change some of the test environment prior to running the test.
Gives the option to have the remote-exec run pre-test setup command.
> Add optional pre_test_setup.

- terraform/common/output.tf
- terraform/ec2/common/linux/main.tf
- terraform/ec2/common/linux/output.tf
- terraform/ec2/common/linux/providers.tf
- terraform/ec2/common/linux/variables.tf
- terraform/ec2/common/linux_reboot/main.tf
- terraform/ec2/common/linux_reboot/variables.tf
- terraform/ec2/creds/main.tf
- terraform/ec2/linux/main.tf
- terraform/ec2/linux_onprem/main.tf
- terraform/ec2/linux_onprem/providers.tf
- terraform/ec2/linux_onprem/variables.tf
Agent is currently not being tested on on-premise environment. 
(ECS and EKS with on-prem instances will be addressed in a separate PR)
Created a new terraform module for onprem usecases, and since most of the file is redundant with the existing ec2 terraform module, refactored them out.
The agent treats a host as onprem instead of EC2 if IMDS is not reachable AND at the same time RUN_AS_AWS environment variable is not set to true. 
This spins up an EC2 instance with IMDS on on purpose even though there's an option to launch with IMDS off. The test run currently needs to ssh into the instance, and if the instance was launched without IMDS connection, for some reason ssh will never be possible. (Behavior not officially documented)
This also allows us to pull down a credential credential …
> Add terraform for onprem and refactor for reuse

- validator/validators/stress/stress_validator.go
This test fails https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/5405319175/jobs/9821174404#step:7:1191
Raises the limit by roughly 3.7% to pass the test
none
> Raising memory data limit for statsd 5000 values per minute test

- validator/validators/stress/stress_validator.go
The tests are flaky since the memory_data for statsd in the 5000 test is right around the current bound. The memory_data which is an indicator of the address space isnt the most critical memory stat and moreover, the 1000, 10000 & 50000 scenarios are all passing with their current bounds.
Increasing the bound for procstat_memory_data for statsd in the 5000 case from 140MB -> 145MB.
N/A
> Increase statsd stress test bound for procstat_memory_data

- terraform/eks/daemon/fluent/d/main.tf
Fluentd on EKS integration test keep failing due to missing log groups
Use a newer `v.1.10.3` fluentd/debian-cloudwatch image.
Manual execution of EKS integ test on a fork.
> Update Fluentd test image to v1.10.3

- terraform/ec2/win/main.tf
- util/common/agent_util_windows.go
Resolves issue with windows 2012 acceptance and restart testing not passing
The `-NoExit` parameter causes the command to not exit after finishing, ultimately timing out. I've removed the calls from `NoExit` from the functions that are called from these tests
Integration testing
> Win2012 test fix

- test/metric_dimension/agent_configs/drop_original_metrics.json
- test/metric_dimension/drop_original_test.go
- test/metric_dimension/metrics_dimension_test.go
We do not have integration test coverage for the drop original metrics feature.
Added a test to the aggregate dimensions tests that covers the standard and wildcard cases.
Ran a minimal test on https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5590470675/jobs/10220269235
>  null_resource.integration_test_run (remote-exec): 2023/07/18 17:30:06 ==============DropOriginalMetrics==============
null_resource.integration_test_run (remote-exec): 2023/07/18 17:30:06 ==============Successful==============
null_resource.integration_test_run (remote-exec): None       Successful
null_resource.integration_test_run (remote-exec): Standard   Successful …
> Add drop original metrics test.

- terraform/ec2/mac/main.tf
- terraform/ec2/mac/variables.tf
Mac tests will not start with gha
Fix the compile of the test and add a default value for user var
terraform apply with the same values as the action.
> Fix Mac Tests Fail To Start GHA

- validator/validators/basic/basic_validator.go
The basic validator is used by the windows feature test to validate metrics and logs. Currently, the log validation just checks that the number of actual log lines is greater than or equal to the number of expected log lines. This will not catch duplicate log lines.
Makes it an equals check instead.
> Change basic validator to check the exact line count.

- validator/validators/basic/basic_validator.go
This reverts commit 10e722ec80df960f2bbf1aba4ec64ab18cb0bb9b.
Expected the test to validate an exact count of log lines, but it doesn't do that. It's to validate the existence of the log lines at all. The same substring shows up multiple times.
Reverts the change.
> Revert "Change basic validator to check the exact line count. (#314)"

- test/metric_value_benchmark/eks_daemonset_test.go
Want to see the log entry and schema for failing emf log. 
Add log line when emf validation fails for log line entry and schema. 
N/A
> Add Log For Entry And Json Schema When Log Validation Fails

- test/metric_value_benchmark/eks_daemonset_test.go
EKS Container insights tests are failing with
```
null_resource.validator (local-exec): 2023/08/01 16:15:59 Metric data input: namespace ContainerInsights, name pod_number_of_container_restarts
null_resource.validator (local-exec): 2023/08/01 16:15:59 Metrics fetched : &{[] <nil> [] {map[{}:-1692101626 {}:0xc00012a580 {}:7cbbf801-6edf-4ced-985c-c4d9bca2b4fe {}:{13919053940034413050 183235282108 0xfcd280} {}:{0 63826503358 <nil>} {}:{[{<nil> false false {map[{}:-1692101626 {}:0xc00012a580 {}:7cbbf801-6edf-4ced-985c-c4d9bca2b4fe {}:{13919053940034413050 183235282108 0xfcd280} {}:{0 63826503358 <nil>}]}}]}]} {}}
null_resource.validator (local-exec): 2023/08/01 16:15:59 metric list is empty
```
The root cause is that the agent when configured for non-enhanced container insights is not …
> remove pod_number_of_container_restarts from eks container insights test

- test/cloudwatchlogs/publish_logs_test.go
- test/ecs/ecs_metadata/ecs_metadata_test.go
- test/fluent/fluent_test.go
- test/metric_value_benchmark/container_insights_test.go
- test/metric_value_benchmark/eks_daemonset_test.go
- test/metric_value_benchmark/emf_test.go
- util/awsservice/cloudwatchlogs.go
- validator/validators/basic/basic_validator.go
Need to be able to detect duplicate logs in the integration tests.
Adds a duplicate log check to the basic validator. Checks that there aren't any logs for the same timestamp and message. Refactored the log validation a bit to evaluate over LogEvents instead of the log messages to retain the timestamp.
Ran the integration tests and failed on the duplicates.
> Add duplicate logs check.

- util/awsservice/cloudwatchlogs.go
Currently, it returns the duplicate error if it doesn't find the message for the timestamp. This means it'll fail on the first log message. It should be the opposite.
Changed the condition.
Checked the log groups for a failing test.
> Fix bug in duplicate check.

- generator/test_case_generator.go
- test/feature/windows/event_logs/agent_config.json
- test/feature/windows/event_logs/parameters.yml
Currently when we have only logs in windows we get duplicate logs. This test handles that case and catches it.
This test creates a terraform instance and runs CWA with only log then check for duplicate logs. 
> [!NOTE]
> This test right now currently fails, which is intentional since the fix for this case has not been merged yet.
Succesfuly run:
Ran the test and checked logs
[Successful  run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6202303125/job/16841325802)
> Adding Logs Only Windows Test

- test/cloudwatchlogs/publish_logs_test.go
- test/cloudwatchlogs/resources/config_auto_removal.json
- test/cloudwatchlogs/resources/config_log.json
- test/cloudwatchlogs/resources/config_log_filter.json
A customer had concerns over the behavior of the agent's auto_removal feature.
They reported the agent was deleting their file BEFORE they created a 2nd file matching the pattern.
This test just verifies the agent DOES NOT delete the monitored file, even if it is restarted after reading to the EOF.
And I added another test case that verifies the agent DOES DELETE prev_file when new_file matching the pattern is found.
Adds a new test case.
- SSH'd into an EC2 instance and run the test from shell:
```
[ec2-user@ip-172-31-18-102 ~]$ cd go/src/github.com/aws/amazon-cloudwatch-agent-test/
[ec2-user@ip-172-31-18-102 amazon-cloudwatch-agent-test]$ go test …
```
> Test auto removal

- generator/test_case_generator.go
- test/emf_concurrent/emf_concurrent_test.go
- test/emf_concurrent/emitter.go
- test/emf_concurrent/testdata/config.json
- util/awsservice/cloudwatchlogs.go
There was an issue with the TCP log receiver corrupting logs on high concurrency. This was fixed as part of  https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/72, but was not pulled into the agent until https://github.com/aws/amazon-cloudwatch-agent/pull/857. This was undetected because it was verified using manual testing.
Add an EMF concurrency test that creates multiple TCP connections to the agent and writes to them concurrently. Runs a log query to determine if any of the logs were corrupted.
Failure from v1.300028.1 (https://github.com/aws/amazon-cloudwatch-agent/commit/6b2589156bc9f27a2c7cb5174073b466163dbd7e) run …
> Add EMF concurrency test to check for log corruption.

- terraform/eks/daemon/emf/main.tf
Leading space characters are not allowed for inline policies, which is causing this test to [fail before it runs](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6618427034/job/18019771184#step:7:85).
Not sure why this is only starting to impact us now. The test [ran fine before](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5904588679/job/16017599809#step:7:65) with `hashicorp/aws v5.13.0` and that [already had this rule](https://github.com/hashicorp/terraform-provider-aws/blob/v5.13.0/internal/verify/validate.go#L162).
Removes the leading spaces and brings it inline with [other inline policies](https://github.com/search?q=repo%3Aaws%2Famazon-cloudwatch-agent-test%20%3C%3CPOLICY&type=code) we have (e.g. …
> Fix EKS EMF test inline policy

- generator/resources/ec2_linux_test_matrix.json
In order to increases adoptions for CloudWatch Agent, we want to validate CloudWatch Agent support for Rocky Linux 8 & 9 so we can expand the customer base to these OS users.
Add Rocky Linux 8 & 9 integration tests to the Linux test suite. Created EC2 Image Pipeline for each OS so they can be automatically generated.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6962001932
> Add Rocky Linux integration tests for CloudWatch Agent

- generator/resources/ec2_linux_test_matrix.json
In order to increases adoptions for CloudWatch Agent, we want to validate CloudWatch Agent support for Alma Linux 8 & 9, AL2023 for both arm64 (Graviton instance) and x86 so we can expand the customer base to these OS users.
- Add Alma Linux 8 x86
- Add Alma Linux 9 x86 
- Add AL2 arm64 (Graviton type instance)
- Add AL2023 x86 
- Add AL2023 arm64 (Graviton type instance)
Run integration tests and validated newly added OS tests all pass
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7091951758/job/19302433042
> Add ALMA Linux and AL2023 tests

- terraform/ec2/mac/main.tf
- terraform/ec2/win/main.tf
No sanity test for darwin and windows
Add sanity check to darwin and windows run
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7426148498
Darwin is missing ami it has nothing to do with this change. The command for darwin is the same as linux so this should be fine. The failing windows tests are for missing ami reasons.
> Add Sanity Test To Darwin And Win

- localstack/docker-compose.yml
- terraform/ec2/localstack/main.tf
- terraform/ec2/localstack/variables.tf
Localstack is on ubuntu
We only want to move a single ami to other partitions and localstack is required
Approve localstack for al2023 arm instance
localstack uses al2023 arm64
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7965568387/job/21745789788
> Move Localstack To AL2023 ARM

- localstack/ls_tmp/snakeoil.conf
No CN dns set
add cn dns to snakeoil.conf
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8023561042/job/21920405681
> add cn dns

- generator/resources/ec2_mac_test_matrix.json
- terraform/setup/main.tf
No testing support for macOS Sonoma arm64 and x86_64
- Add testing support for macOS Sonoma arm64 and x86_64
```
vtayyare@88665a54407b Downloads % ssh -i "test_macos.pem" ec2-user@ec2-52-89-104-182.us-west-2.compute.amazonaws.com
Last login: Tue Mar  5 20:54:28 2024 from 205.251.233.236
┌───┬──┐   __|  __|_  )
│ ╷╭╯╷ │   _|  (     /
│  └╮  │  ___|\___|___|
│ ╰─┼╯ │  Amazon EC2
└───┴──┘  macOS Sonoma 14.3
ec2-user@ip-172-31-40-218 ~ % sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status
{
"status": "running",
"starttime": "2024-03-05T20:55:34+0000",
"configstatus": "configured",
"version": "1.300033.0b462"
}
```
``` …
```
> add macOS sonoma

- generator/resources/ec2_linux_test_matrix.json
We want to support newer version of debian for our customers. In order to support it we want to test it with our integration test.
I have added debian-12 to our integration test by adding it to generator configs and making a custom image builder.
I ran the linux integration test [here](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8271534214)
> Added debian-12 to our integration test

- test/app_signals/resources/metrics/client_producer.json
- test/app_signals/resources/metrics/server_consumer.json
Current server_consumer.json and client_producer.json generates invalid app signal metrics. The metrics Latency, Error, and Fault should be an object but instead the request sent to the agent generated the metrics to just be zero.
It is a really small change, the data type of each metric is sum but instead it should be the type exponential_histogram. This is the correct type and it generates correct app signal metrics.
Sent json's to the agent and checked the console which had the correct format of the metrics.
> Changing data type of appsignals integ test

- test/canary/canary_test.go
We want a canary test that downloads the agent the same way that users do... From the public S3 URL.
The test is now hardcoded to test the public global S3 download link.
Future improvement can be made to test against a list of S3 URLs (regional S3 links).
Other than that the test remains the same.
It verifies the agent can be downloaded, installed, started with a basic config, and that the version is correct.
It reports custom metrics to the test account so we can add alarms on those to make sure all of the above is working.
- Ran the test on an EC2:
```
dev-dsk-adamym-1d-90bc66b6 % AWS_REGION=us-east-1 go test ./ -count=1 -computeType=EC2 -v
=== …
```
> Update canary test to use public S3 download link.

- generator/resources/eks_daemon_test_matrix.json
- generator/test_case_generator.go
- terraform/eks/daemon/gpu/main.tf
EKS GPU test was not using a gpu instance type
Use GPU instance type for EKS GPU test
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8913045939/job/24478223654
> EKS Nvidia Test Use A GPU Instance Type

- generator/test_case_generator.go
The tests covered in this test repo are also covered in the end-to-end tests: https://github.com/aws/amazon-cloudwatch-agent/blob/main/.github/workflows/application-signals-java-e2e-ec2-asg-test.yml
These tests are more robust, as they use the adot sdks to send elemetry to the agent. The tests in this repo are also stale as a result of the schema changes introduced in https://github.com/aws/amazon-cloudwatch-agent/commit/4193fa17b3759581753480cd378f0c6ef47043bb
This PR disables testing for application signals. These tests are wasting resources to test features covered in the workflow linked above.
N/A
> Disable application signals testing in favor of end-to-end tests

- test/metric/container_insights_util.go
Container Insights integration test fails with a panic when a cluster is not ready with target metrics
- Add a precheck before calling `rand.Intn`
> Fix panic when metrics not yet ready in a cluster

- generator/resources/ec2_mac_test_matrix.json
- generator/resources/ec2_windows_test_matrix.json
- terraform/setup/main.tf
We want to remove end-of-life OSes code as they're end-of-life.
Removed references for end-of-life OSes in this package.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/9369085049
- EC2WinIntegrationTest for win-2012 and EC2DarwinIntegrationTest for macOS Big Sur are no longer present.
> Removing end-of-life OSes.

- test/metric_value_benchmark/agent_configs/jmx_kafka_config.json
Currently the `metric_value_benchmark` test is failing due to the increase in Kafka metrics to 60 seconds. 
Modified test agent config to include `"metrics_collection_interval": 10`
It passed with 10 seconds interval in this integration test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/9681807856/job/26713593403 
And it started failing when we update to 60 seconds seen in this integration test: 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/9717891459/job/26825009743
> Update metrics_collection_interval for Kafka to 10 seconds

- generator/resources/ec2_linux_test_matrix.json
We want to remove end-of-life OSes code as they're end-of-life.
| OS Name   | End Of Life   | Source                                                                                                                                                                                                 |
|-----------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| debian-10 | June 30, 2024 | [link](https://www.debian.org/News/2024/20240615)                                                                                                                                                      |
| centos-7  | June 30, 2024 | …
> Removed End of Life OSes (debian-10,centos-7,rhel7)

- test/metric_value_benchmark/eks_resources/util.go
We are adding 2 new metrics per pod `pod_cpu_usage_total` & `pod_memory_working_set`
PR: https://github.com/aws/amazon-cloudwatch-agent/pull/1294
Updating integrationTests for the newly added metrics.
There is an issue with fetching other metrics in integration Tests, so the complete workflow is not successful: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10408457860/job/28826102473
> Updating integration tests for newly added metrics

- terraform/eks/daemon/awsneuron/variables.tf
We had removed the ami_type and instance_type variables from the variables.tf file since they were not used but the terraform apply in the agent needs these variables, adding them back so that the terraform apply doesn't fail
agent code : 
```
terraform init
if terraform apply --auto-approve \
-var="test_dir=${{ matrix.arrays.test_dir }}"\
-var="cwagent_image_repo=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_INTEGRATION_TEST_REPO }}" \
-var="cwagent_image_tag=${{ github.sha }}" \
-var="ami_type=${{ matrix.arrays.ami }}" \
-var="instance_type=${{ matrix.arrays.instanceType }}" \
-var="k8s_version=${{ matrix.arrays.k8s_version }}"; then
terraform destroy -auto-approve
else
terraform destroy -auto-approve && exit 1
fi
```
- adding back ami_type and instance_type in neuron integ test …
> add removed variables for ami_type and instance_type

- generator/resources/ec2_linux_test_matrix.json
Add Ubuntu 24.04 support
Test run in the agent repo: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10964690286
The test was targeting only ubuntu 23 and 24 for comparison.
> Add ubuntu24 to ec2 linux test suite

- generator/test_case_generator.go
- terraform/eks/daemon/entity/main.tf
- terraform/eks/daemon/entity/providers.tf
- terraform/eks/daemon/entity/variables.tf
- test/entity/entity_test.go
- util/awsservice/cloudwatchlogs.go
FluentBit has a new feature to emit CloudWatch logs with entity field which helps users navigate between their telemetry in the CloudWatch console. We want to add an integration test which helps us validate this behavior.
This PR focuses on the test scenario where FluentBit falls back to using K8sWorkload as the service name and uses default environment name. 
- Add new terraform that uses helm chart to set up the cluster
- Create a worker pod that output log every second
- Add test code to validate the entity fields contain the necessary values.
Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11790939699/job/32939527206 (Ran …
> Add EKS integration test for FluentBit log emission with Entity field

- test/metric/metric_validation_util.go
- test/metric_value_benchmark/agent_configs/jmx_tomcat_jvm_config.json
- test/metric_value_benchmark/jmx_tomcat_jvm_test.go
We have failing JMX tests throughout out integration tests for multiple OSes. Here is a [failed run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11169916913/job/31051812062#step:7:8275) that shows the test failing on these metrics in a previous run—specifically the garbage collection and tomcat metrics.
- Extended agent run time from 2 to 5 minutes and set `metrics_collection_interval` to 60 seconds to better capture infrequent metrics (like `jvm.gc.collections.elapsed` and `jvm.gc.collections.count`)
- Added java commands to enable the mbean registry to properly expose tomcat metrics
- Some tests were failing because the average value of metrics fell slightly outside of the bounds (+/- 10%). I upped this to 15%.
By submitting this pull request, I confirm that you can use, …
> Fix failing JMX tests

- terraform/eks/daemon/entity/main.tf
- test/entity/entity_test.go
FluentBit has a new feature to emit CloudWatch logs with entity field which helps users navigate between their telemetry in the CloudWatch console. We want to add an integration test which helps us validate this behavior.
This PR focuses on the test scenario where FluentBit uses Instrumentation service name source from AppSignal and uses default environment name.
- Add EKS integration test for FluentBit emitting service name with source `Instrumentation`
Integ test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11826261947/job/32991773276
> Add EKS integration test for FluentBit log emission with Instrumentation source

- generator/test_case_generator.go
- terraform/eks/daemon/efa/main.tf
- terraform/eks/daemon/efa/providers.tf
- terraform/eks/daemon/efa/variables.tf
- test/efa/efa_test.go
- test/efa/resources/config.json
- test/metric_value_benchmark/eks_resources/test_schemas/container_efa.json
- test/metric_value_benchmark/eks_resources/test_schemas/node_efa.json
- test/metric_value_benchmark/eks_resources/test_schemas/pod_efa.json
- test/metric_value_benchmark/eks_resources/util.go
This PR adds new integration test for AWS EFA. 
This is pretty similar to exsting EKS daemonset test suite such as GPU and Neuron. One addition is that there is an `initContainer` in the agent pod which creates an empty directory then build EFA data structure with a dummy device (`device1`). These newly created files and directories get mounted to the agent container where EFA receiver is expecting them. Below is the structure that EFA receiver expects:
```
/sys/class/infiniband/<device name>
└── ports
└── 1
└── hw_counters
├── rdma_read_bytes
├── rdma_write_bytes
├── rdma_write_recv_bytes
├── rx_bytes
├── rx_drops
└── tx_bytes
```
Additionally, the init container runs `chmod` on `infiniband/` as the receiver expects the folder to be writable by the root user only. 
Pod and Container …
> Add integration test for EFA

- generator/resources/eks_addon_test_matrix.json
- generator/resources/eks_daemon_test_matrix.json
- generator/resources/eks_deployment_test_matrix.json
- generator/test_case_generator.go
- terraform/eks/addon/gpu/main.tf
- terraform/eks/addon/gpu/variables.tf
- test/gpu/nvidia_test.go
- test/metric/container_insights_util.go
GPU E2E Integ test is failing with missing metrics and dimensions
- Reorder `kubectl` apply commands so that GPU burn pod starts after nvidia device plugin is installed
- Update metrics-dims sets to the latest to include or drop GPU count metrics and their names
- Update EKS and Addon versions to the latest
- Use variables from the generated test matrix json instead hard-coded values
Github test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12127752653
```
2024/12/02 15:46:15 >>>>>>>>>>>>>><<<<<<<<<<<<<<
2024/12/02 15:46:15 >>>>>>>>>>>>>>Successful<<<<<<<<<<<<<<
2024/12/02 15:46:15 ==============EKS_GPU_NVIDIA============== …
```
> Fix GPU E2E integ test

- test/metric_value_benchmark/eks_resources/util.go
Metrics benchmark integ tests are failing example: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11959277199/job/33340769914
Update the list of metrics used for validations and the dimension sets they get validates with
```
2024/12/03 13:24:17 >>>>>>>>>>>>>><<<<<<<<<<<<<<
2024/12/03 13:24:17 >>>>>>>>>>>>>>Successful<<<<<<<<<<<<<<
2024/12/03 13:24:17 ==============EKSContainerInstance==============
2024/12/03 13:24:17 ==============Successful==============
ClusterName-InstanceId-NodeName                           Successful  
node_status_allocatable_pods                              Successful  
node_network_total_bytes …
```
> update list of ContainerInsights metrics used for validations

- generator/resources/eks_addon_test_matrix.json
- terraform/eks/addon/gpu/main.tf
- terraform/eks/addon/gpu/variables.tf
drop `addon_version` variable to let the addon module to install the latest
> drop addon version to pick the latest

- msi/tools/amazon-cloudwatch-agent.wxs
The CloudWatch Agent service on Windows fails to start automatically on certain custom AMIs created using Windows sysprep. This issue occurs due to a race condition between the agent's startup and the initialization of network drivers during system boot.
This PR modifies the CloudWatch Agent's service configuration to improve its startup reliability:
1. Removed the dependency on the "LanmanServer" service.
2. Added new service dependencies: "Tcpip" and "Dnscache".
3. Implemented more detailed failure action settings in the service configuration.
4. Added `Start='install'` to the `ServiceControl` element.
**Rationale:**
- **Removed "LanmanServer" dependency:** Eliminates a non-critical wait during startup, reducing potential delays.
- **Added "Tcpip" and "Dnscache" dependencies:** Ensures …
> [Enhancement] Enhance CloudWatch Agent Startup on Windows AMIs via Dependency Updates

- msi/tools/amazon-cloudwatch-agent.wxs
We encountered an issue with Docker on Windows where the automatic starting of the agent service during installation was interfering with the Docker environment.
- Removed the build flag responsible for auto-starting the agent service from the WXS file.
- This change prevents the agent service from starting automatically upon installation with msi on Windows systems.
By removing the automatic start of the agent service, we aim to resolve conflicts with Docker environments on Windows, allowing for a smoother installation process.
- Ran integration tests and compared results to the main branch:
- Main branch test: [Run #12323241718](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12323241718)
- This change: [Run #12658779476](https://github.com/aws/amazon-cloudwatch-agent/actions …
> Remove starting Agent Service on Installation on Windows

- generator/resources/ec2_linux_test_matrix.json
Ubuntu-23 is End of Life starting since 11 Jul 2024. We no longer support this Operating System; thus, we are removing it from our test suite.
Remove Ubuntu-23 from our test matrix
Test run:https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12680590830 
In the test run you can see ubuntu-23 no longer exists.
> Remove End of Life OS: ubuntu-23

- test/metric_value_benchmark/eks_resources/util.go
Our EKS integration test is failing for metric value benchmark.
We are tracking metric that is not published. Since this is a positive test we won't have crash loop back off status in any of pods so tracking this metric isn't necessary.
Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12813906231
> Fix EKS integration test by removing unnecessary metric

- environment/eksdeploymenttype/eks_deployment_type.go
- generator/test_case_generator.go
- terraform/eks/daemon/credentials/pod_identity/main.tf
- terraform/eks/daemon/credentials/pod_identity/providers.tf
- terraform/eks/daemon/credentials/pod_identity/variables.tf
- test/metric/container_insights_util.go
- test/metric_value_benchmark/eks_daemonset_test.go
- test/metric_value_benchmark/metrics_value_benchmark_test.go
Pod identity credential support is added to CloudWatch Agent and FluentBit, however we lack integration test.
- Add new terraform folder for credential related testing
- Add new test case when deployment strategy is pod identity. This mode only checks for basic Container Insight metrics that are present on any EKS cluster.
- Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12797706927/job/35689119613. Note that other test failures were there before this change and it is not in scope for fixing as part of this PR.
- integ test run rev2: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12952146544
> Add pod identity credential integration test

- terraform/eks/daemon/app_signals/variables.tf
- terraform/eks/daemon/fluent/bit/variables.tf
- terraform/eks/daemon/fluent/common/variables.tf
- terraform/eks/daemon/fluent/d/variables.tf
- terraform/eks/daemon/fluent/windows/2019/variables.tf
- terraform/eks/daemon/fluent/windows/2022/variables.tf
- terraform/eks/daemon/fluent/windows/variables.tf
- terraform/eks/daemon/statsd/variables.tf
- terraform/eks/daemon/variables.tf
- terraform/eks/daemon/windows/2019/variables.tf
- terraform/eks/daemon/windows/2022/variables.tf
- terraform/eks/daemon/windows/variables.tf
- terraform/eks/deployment/variables.tf
EKS 1.24 is on extended support until 1/31/2025. We can no longer create clusters past this date.
Also, EKS 1.32 is now GA.
Update EKS versions used for our test suite.
N/A
> Update EKS 1.24 -> 1.32

- test/emf/ecs_resources/ec2_launch/daemon/ecs_taskdef.tpl
Our ECS EMF integration tests are currently failing. This is because the ubuntu socat image referenced in our code no longer exists.  
The code now references a public alpine image that comes preinstalled with the necessary packages (curl, netcat, bash shell).  
Integration Test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13162186862
ECS EMF Test 1: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13162186862/job/36733536164
ECS EMF Test 2: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13162186862/job/36733551094
> Fix ECS EMF integration tests

- terraform/ec2/common/linux/main.tf
- terraform/ec2/linux/main.tf
Multiple tests are failing because the instances are being rebooted in the middle of setup or while the test is running, which hides actual failures.
```
null_resource.integration_test_run (remote-exec): Broadcast message from root@ip-XXX-XX-XX-XX.us-west-2.compute.internal (Wed 2025-01-22 01:27:02 UTC):
null_resource.integration_test_run (remote-exec): The system is going down for reboot at Wed 2025-01-22 01:28:02 UTC!
```
- Add cancellation for rebooting instances during tests (temporary fix that should be removed after root cause)
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13212770564
> [temp fix] Add cancellation for rebooting instances during tests

- README.md
- generator/resources/ec2_linux_test_matrix.json
We have EOL OSes that we no longer support in our integration test matrix
This PR removes the EOL OSes that are no longer supported
> Remove EOL OSes from our test matrix

- terraform/ec2/win/main.tf
Windows integration tests were failing due to being unable find `validator.exe`
- Updated validator install path to explicit path of C:\\validator.exe
- Updated commands that call validator.exe as well.
Passing tests that are able to run validator.exe
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13461232545/job/37716968400
Previously failing test that could not find validator.exe
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13421207184/job/37494425152
> [Windows] Update validator install path to C:\\validator.exe

- generator/resources/ec2_linux_test_matrix.json
We have EOL OSes(sles-12) that we no longer support in our integration test matrix
This PR removes the EOL OSes(sles-12) that are no longer supported
> [EOL OS] Remove SLES-12 from Test Matrix

- terraform/ec2/assume_role/main.tf
- terraform/ec2/creds/main.tf
- terraform/ec2/linux_onprem/main.tf
Multiple tests are failing because the instances are being rebooted in the middle of setup or while the test is running, which hides actual failures.
```
null_resource.integration_test_run (remote-exec): Broadcast message from root@ip-XXX-XX-XX-XX.us-west-2.compute.internal (Wed 2025-01-22 01:27:02 UTC):
null_resource.integration_test_run (remote-exec): The system is going down for reboot at Wed 2025-01-22 01:28:02 UTC!
```
- Add cancellation for rebooting instances during tests (temporary fix that should be removed after root cause)
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13212770564
> Add cancellation for rebooting instances during tests for all environments

- generator/test_case_generator.go
The current implementation of the test case generator does not support generating a descriptive test name for each test case. This makes it difficult to quickly identify the purpose or category of a test from its name. 
This change introduces a new field `TestName` to the `matrixRow` struct. The `generateTestName` function is added to generate descriptive test names based on the directory structure of the test cases. The test names are further enhanced by prefixing them with the OS and test type when available.
The changes have been tested by running the `genMatrix` function with various test configurations. The generated test names were verified …
> Enhance Test Case Generator with Descriptive Test Names

- test/metric_value_benchmark/metrics_value_benchmark_test.go
- util/awsservice/constant.go
Multiple China/ITAR tests are failing due to an UnrecognizedClientException when calling AWS APIs.
China
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13507749182/job/37741584109#step:7:1326
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13507749182/job/37741587895#step:7:1253
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13507749182/job/37741587403#step:7:2236
ITAR
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13533128422/job/37819655349
This change configures the AWS clients to use the actual region instead of always defaulting to `us-west-2`. 
Integration test run: …
> Fix the Unrecognized Client exception for China/ITAR tests

- terraform/ec2/assume_role/main.tf
- terraform/ec2/creds/main.tf
Multiple tests are failing because the instances are being rebooted in the middle of setup or while the test is running, which hides actual failures.
```
null_resource.integration_test_run (remote-exec): Broadcast message from root@ip-XXX-XX-XX-XX.us-west-2.compute.internal (Wed 2025-01-22 01:27:02 UTC):
null_resource.integration_test_run (remote-exec): The system is going down for reboot at Wed 2025-01-22 01:28:02 UTC!
```
- Add cancellation for rebooting instances during tests (temporary fix that should be removed after root cause)
- Reference: https://github.com/aws/amazon-cloudwatch-agent-test/pull/473
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. ✅
> Readd the fix to cancel reboots

- test/metric_value_benchmark/eks_daemonset_test.go
Test for metric_value_benchmark seems to be flaky because metrics pop up eventually on cloudwatch, increasing time duration from 3->5 minutes.
Tested locally by running test 20 times, but since tests weren't isolated. Ran terraform apply 10 time in this run:
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13937761021 where test seems to pass and only fail because we have reach IAM role limit.
Test run (has 10 test running - all passing)
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13948719906/job/39042317798
> Bumping time duration of eks integ test

- terraform/eks/daemon/app_signals/main.tf
- terraform/eks/daemon/awsneuron/main.tf
- terraform/eks/daemon/efa/main.tf
- terraform/eks/daemon/emf/main.tf
- terraform/eks/daemon/fluent/common/main.tf
- terraform/eks/daemon/fluent/windows/main.tf
- terraform/eks/daemon/gpu/main.tf
- terraform/eks/daemon/main.tf
- terraform/eks/daemon/statsd/main.tf
- terraform/eks/daemon/windows/main.tf
- terraform/eks/deployment/main.tf
We need these extra permissions for cloudwatch-agent-role in order to fix eks_daemon test:
Passing test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13980738612/job/39145280460
This pr is where the permissions were take from: https://github.com/aws-samples/amazon-cloudwatch-container-insights/pull/188
> Adding endpoint slices permission to Cluster Role

- terraform/eks/daemon/fluent/windows/main.tf
- terraform/eks/daemon/windows/main.tf
There is a common error for daemon (https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13932872602/job/38994139853) and fluent (https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13980566448/job/39144772679) tests for Windows.
```
error: deployment "windows-test-deployment" exceeded its progress deadline
```
- Increase the timeout for deployments.
[View Workflow Run #14029002987](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14029002987)
> Increase timeout for daemon and fluent deployments for Windows

- test/metric_value_benchmark/metrics_value_benchmark_test.go
The check to see if the region is `us-west-2` does not work as intended.
This PR fixes the region check.
Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14043851158/job/39320336163#step:7:3288
> Fix region check for entity metric_value_benchmark test

- terraform/ec2/userdata/main.tf
The ol9-userdata integration test is failing: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13975282090/job/39127808918.
The reason is that it is trying to access the `verifyUnixCtlScript.sh` file before its parent repository, `amazon-cloudwatch-agent-test`, is properly cloned.
The git clone occurs in [template_file.init](https://github.com/aws/amazon-cloudwatch-agent-test/pull/488/files#diff-a7be248a9b77a41abd209a2cf32cc4a4f3fd20974a91c76434a28dad80a90279R121-R131) with the [install_and_start_agent.sh](https://github.com/aws/amazon-cloudwatch-agent-test/blob/6b0a1a77338247831622d0ebe99c339864c7acf1/terraform/ec2/userdata/install_and_start_agent.sh) script.
- Make sure `null_resource.integration_test` depends on `template_file.init`.
By submitting this pull request, I …
> Fix race condition for ol9 userdata test

- test/metric_value_benchmark/jmx_kafka_test.go
The metric value benchmark test fails because some amis already have directory apache-zookeeper-3.8.4-bin/data created so the jmx command fails with exit status 1. Adding a remove to make sure the directory doesn't exist fixes this issue. 
Failing run (before change): https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14092963651/job/39474178977
Passing run (after change) : [aws/amazon-cloudwatch-agent/actions/runs/14096842424/job/39485825767](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14096842424/job/39485825767)
> Updating metric value bench mark test failure

- test/amp/amp_test.go
Currently, the CloudWatch Agent uses the [prometheusremotewrite exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter) to send metrics to Amazon Managed Prometheus. It does not support delta metrics so the metrics are dropped:
> Non-cumulative monotonic, histogram, and summary OTLP metrics are dropped by this exporter.
This issue was discovered while updating the AMP integration test: https://github.com/aws/amazon-cloudwatch-agent-test/pull/465#issue-2864562335
The agent is being updated to support delta metrics when sending to AMP destinations: https://github.com/aws/amazon-cloudwatch-agent/pull/1624
Check for newly supported delta counter (sum) and delta histogram metrics in AMP integration test.
By submitting this …
> Check for delta metrics

- validator/validators/stress/stress_validator.go
Stress tests are occasionally failing.  [Example Run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14098144880/job/39489346003)
Adjusts several thresholds to a value slightly above what was reported by recent test runs.  Calculations below.
New values used in the tests are slightly above the values in the column `Calculated Actual Value`
||**modifier**|**Test Actual Value**|**Calculated Actual Value (Used in code)**|**Limit Test**|**Calculated Limit Value**|
|:---|:---|:---|:---|:---|:---|
||0.3|||||
|||||||
|50000||||||
||net_packets_sent|146|112.3076923|130|100|
|statsd|net_bytes_sent|1814914|1396087.692|2210000|1700000| …
> Adjust stress test thresholds to account for occasional fluctuations in test runs

- generator/test_case_generator.go
- test/metric_value_benchmark/jmx_kafka_test.go
Currently the ca_bundle test is flaky, we need to skip this test until it is fixed in order to unblock other prs.
Example: https://github.com/aws/amazon-cloudwatch-agent/pull/1629. The test is currently being fixed and once that is fixed, ca_bundle test will be added.
Flaky test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14234895874/job/39892482506
> Skipping Ca_bundle test until fixed

- test/e2e/envutils.go
- test/e2e/jmx/jmx_test.go
- test/e2e/jmx/resources/cwagent_configs/jvm_tomcat.json
- test/e2e/jmx/resources/sample_apps/tomcat.yaml
- test/e2e/testutils.go
- test/e2e/utils/helm_manager.go
- test/e2e/utils/k8s_manager.go
This pull request refactors the end-to-end tests in the `amazon-cloudwatch-agent-test` repository. The updates address inconsistencies in resource management and traffic generation, streamline the deployment process with Kubernetes and Helm, and improve test reliability.
- **Traffic Generation**: Replaced the old `GenerateTraffic` method with k6s, offering a more robust and efficient load generation approach.
- **Helm Management**: Introduced generic Helm management that accepts specific values, simplifying deployments and reducing reliance on hardcoded commands.
- **Service Configuration**: Changed the service type from `NodePort` to `ClusterIP` as it is better suited with k6s for a safer and more controlled testing environment.
- **Resource Application and Destruction**: Refactored …
> Refactor e2e Tests Traffic Generation and Generic Helm Management

- .github/workflows/build-check.yml
- clean/README.md
- clean/clean_ami/clean_ami.go
- clean/clean_auto_scaling_groups/clean_auto_scaling_groups.go
- clean/clean_dedicated_host/clean_dedicated_host.go
- clean/clean_ebs/clean_ebs.go
- clean/clean_ecs/clean_ecs.go
- clean/clean_eks/clean_eks.go
- clean/clean_file_system/clean_file_system.go
- clean/clean_host/clean_host.go
- clean/clean_iam_roles/clean_iam_roles.go
- clean/clean_iam_roles/clean_iam_roles_test.go
- clean/clean_launch_configuration/clean_launch_configuration.go
- clean/clean_log_group/clean_log_group.go
- clean/clean_log_group/clean_log_group_test.go
- clean/clean_security_group/clean_security_group.go
- clean/clean_security_group/clean_security_group_test.go
- clean/clean_util.go
- go.mod
- go.sum
The tool/clean module contains all our cleaner scripts to purge any orphaned resources created by our integ tests. Moving this over from the agent repo to the test repo.
GH run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14090243153
> Migrate tool/clean from agent repo

- generator/test_case_generator.go
- terraform/ec2/linux/main.tf
- test/emf_prometheus/common.go
Currently test validates before metrics appear sometimes so in order to fix this issue adding a retry to make sure that test are not flaky:
Here is the flaky test fail: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14673647451/job/41185739077 (test retried)
Here is the test run that shows test passing 10+ times: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14710259879/job/41280752001
> Adding retries to Prometheus EMF tests

- generator/test_case_generator.go
Currently the otlp and metric value benchmark selinux test is failing and is blocking prs. Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14888797510/job/41815609374. These test will be added back once they are fixed.
> Skipping OTLP and MVB SELinux test to unblock PRs

- terraform/ec2/userdata/main.tf
Userdata test is failing for ol9
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15330575566/job/43136394248?pr=1706
Increases timeout during setup of test environment.
Test run completed successfully in local environment
> Increase timeout in userdata test

- terraform/ec2/userdata/main.tf
Currently OL9 Userdata test fails with this message
`go.mod file not found in current directory or any parent directory; see 'go help modules'`
Added git clone to make sure test directory exists
> Fix userdata test failure

- validator/validators/stress/stress_validator.go
Currently sometimes we only get 288 sample count which is not in the bounds of [290-300]. Here is the a failing test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15740503860/job/44364409368
Changing bound from [290-300] to [285-300] in order to make test not flaky.
> Stress test sample count bound variance increase

- generator/test_case_generator.go
- terraform/ecs_ec2/daemon/main.tf
- terraform/ecs_fargate/linux/main.tf
- test/ecs/ecs_sd/ecs_servicediscovery_runner.go
- test/ecs/ecs_sd/ecs_servicediscovery_test.go
- test/ecs/ecs_sd/ecs_servicediscoveryrunner.go
- test/statsd/statsd_test.go
- test/test_runner/ecs_test_runner.go
We need to test ECS servicediscovery against ecs_ec2 as well as ecs_fargate. Adding the missing scenario
Add ecs_sd test dir to the ecs_ec2 test matrix in the generator
Running integ tests: 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15828254148
Test run now includes new test `ecs_ec2_daemon:ecs_ecs_sd_test`
> Test ECS Servicediscovery on ecs ec2

- terraform/eks/daemon/credentials/pod_identity/main.tf
- terraform/eks/daemon/credentials/pod_identity/providers.tf
- terraform/eks/daemon/entity/main.tf
- terraform/eks/daemon/entity/providers.tf
- terraform/eks/deployment/main.tf
Update `exec` element under k8s for helm struct as variable type. Ref https://registry.terraform.io/providers/hashicorp/helm/latest/docs#exec-plugins
> update k8s struct vars

- terraform/eks/daemon/credentials/pod_identity/main.tf
- terraform/eks/daemon/entity/main.tf
`helm_release` is failing by missing cloned helm charts
- Change `null_resource` to `external` to make sure the completion of `git clone` step of the charts
Run `terraform apply` locally
```
helm_release.aws_observability: Still creating... [10s elapsed]
helm_release.aws_observability: Still creating... [20s elapsed]
helm_release.aws_observability: Creation complete after 29s [id=amazon-cloudwatch-observability]
```
> Switch null_resource to external for helm git clone step

- terraform/ecs_fargate/linux/main.tf
- test/ecs/ecs_sd/ecs_servicediscovery_runner.go
- test/ecs/ecs_sd/ecs_servicediscovery_test.go
- test/ecs/ecs_sd/resources/config_service_name_list.json
- test/ecs/ecs_sd/resources/config_task_definition_list.json
- test/test_runner/ecs_test_runner.go
Current Service Discovery testing only covers config via DockerLabel. This gap prevents us from effectively determining if any changes impact ECS Service Discovery functionality configured using ECS Task Definition List or ECS Service Name List configs.
This change introduces additional cloudwatch agent configs for the remaining scenarios, and updates the code to loop through each one and validate published CloudWatch Logs.
This change also includes minor updates to error logging for debugging
Validated ECS_SD tests succeed against ECS_Fargate and ECS_EC2. No other ECS tasks are broken: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/164 …
> Add ECS Service Discovery Tests - TaskDefList & ServiceNameList 

- terraform/ec2/win/main.tf
Currently this test seems to be flaky due to not having amazon-cloudwatch-agent-ctl.ps1 installed here's the error message:
`amazon-cloudwatch-agent-ctl.ps1 not found after installation`. Failing test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/16998567192/job/48225508375
Currently we just check once if the file exists, now we are adding a retryer which retries 30 times sleeps 10 second each time to wait to see if amazon-cloudwatch-agent-ctl.ps1 is found. This fixes the flakiness as it seems the test is just checking before `amazon-cloudwatch-agent-ctl.ps1` is installed. 
Ran test 6 times in this run (all passing): https://github.com/aws/amazon-cloudwatch-agent/actions/runs/17052849215/job/48344452928
> Fixing win-11 event-log flaky integ test

- generator/test_case_generator.go
- test/metric/container_insights_util.go
Minor logging improvement for failed tests. Prior to this change, the summary at the bottom would print the Dimensions key, but the detailed error logging further up would print the metric name - making it hard to correlate the two.
With the change, we now print both the metrics and the dimensions in both places.
Before change:
```
ValidateMetrics failed with missing metric: container_filesystem_usage
ValidateMetrics failed with missing metric: container_filesystem_available
ValidateMetrics failed with missing metric: container_filesystem_utilization
...
module.windows.null_resource.validator (local-exec): ClusterName        Failed …
```
> Better error logging for EKS CI test failures

- test/cloudformation/resources/AmazonCloudWatchAgent/inline/amazon_linux.template
The current Cloudformation tests deploy a template that uses a fixed, old version of AL2023.
- Updated the template to use SSM to retrieve the latest version of the AL2023 AMI.
Deployed the Cloudformation stack and got the following value for `InstanceAMI`:
**OLD**
```
{
"Images": [
{
"Architecture": "x86_64",
"CreationDate": "2023-05-01T19:14:55.000Z",
"ImageId": "ami-04e914639d0cca79a",
"ImageLocation": "amazon/al2023-ami-2023.0.20230503.0-kernel-6.1-x86_64",
"ImageType": "machine",
"Public": true,
"OwnerId": "137112412989",
"PlatformDetails": "Linux/UNIX",
"UsageOperation": "RunInstances",
"State": "available",
"BlockDeviceMappings": [
{ …
```
> Update CloudWatch Agent installation template to use latest AL2023 AMI.

- test/otlp/otlp_test.go
OTLP integ tests are failing in some cases
Add `log_stream` values replacement logic for agent yaml. Burrowing the idea from https://github.com/aws/amazon-cloudwatch-agent-test/blob/main/test/detailed_metrics/detailed_metrics_test.go#L84
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/18020314883
> fix flaky log validation by targeting log stream with instanceId

- generator/resources/ec2_linux_test_matrix.json
- test/metric_value_benchmark/net_test.go
Add support for RHEL10.
We verify support for RHEL10 by including the OS in our suite of testing.
> Red Hat removed the Docker container engine and the docker command from RHEL 10. 
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html-single/building_running_and_managing_containers/index#running-containers-without-docker
As a result, we use the `ens5` network interface instead of the `docker0` network interface for our RHEL10 network tests.
Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/18047091319
> Add RHEL10 OS support

- generator/resources/ec2_linux_test_matrix.json
Add support for Ubuntu 25.
We verify support for Ubuntu 25 by including the OS in our suite of testing.
Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/18148334626
> Add support for Ubuntu 25

- generator/resources/ec2_linux_test_matrix.json
For testing we use both t3 and t3a instances. These are both x86 instances but with different processors. According to [docs](https://aws.amazon.com/ec2/instance-types/t3/), they are identical but t3a is ~10% cheaper. We will now use the t3a.medium instance type where we were previously using the t3.medium type. 
Note: The debian12 and some of the al2 and al2023 tests are unchanged to not use the t3a.medium instance type due to being more resource-intensive. These tests failed when run on a t3a.medium.  
Integ test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/18225099540
> Use t3a.medium in integ tests
