go.mod
go.sum
test/cwl_util.go
test/cwm_util.go
test/metric/cpu.go
test/metric/metric_value_query.go

Based on feedback https://github.com/aws/amazon-cloudwatch-agent-test/pull/2

Remove unnecessary dependencies

---

dev_manuals/Learning_Testing_Workflow.md
terraform/ec2/win/main.tf
terraform/ec2/win/variables.tf

- Add document for ECSFargateIntegrationTest
- Fix EC2NvidiaGPUIntegrationTest
- change for agent repo staged in my agent personal fork: https://github.com/ChenaLee/amazon-cloudwatch-agent/commit/71df6eef66a76dbf5d7eddfb7d1417b85dfaf456

Add document for ECSFargateIntegrationTest and Fix for EC2NvidiaGPUIntegrationTest

---

terraform/ec2/README.md

Fix instruction for fork test branch tags

---

.github/CODEOWNERS

Add codeowners of the repository

---

terraform/ec2/README.md

*Issue #, if available:*
*Description of changes:*

Fix test readme for successful ecs tests

---

terraform/ecs/linux/main.tf

ECS test has always failed in my fork so didn't catch this, but needs this change so ecs tests continue to succeed in the main repo

Fix ecs test

---

test/ecs/ecs_metadata/ecs_metadata_test.go

Update references of CWA to main branch

Update references of CWA to main branch

---

generator/test_case_generator.go
test/agent_util_linux.go
test/run_as_user/resources/cwagent.json
test/run_as_user/resources/default.json
test/run_as_user/resources/root.json
test/run_as_user/run_as_user_test.go

Need to confirm run as user works for private agent repo.
Add run as user test
go test ./test/run_as_user/ -p 1 -timeout 30m -v --tags=integration

Add Run As User Test

---

test/ca_bundle/ca_bundle_test.go
test/ca_bundle/resources/integration/ssl/with/combine/bundle/config.json
test/ca_bundle/resources/integration/ssl/with/original/bundle/config.json
test/ca_bundle/resources/integration/ssl/without/bundle/config.json
test/ca_bundle/resources/integration/ssl/without/bundle/http/config.json

CA bundle tests fail on certain os due to timer issue.
Reduce chance of timer issue by decreasing time to publish
[_Describe what tests you have done._
](https://github.com/sethAmazon/amazon-cloudwatch-agent/actions/runs/3567075609/jobs/5994318858)

Fix CA Bundle Test

---

generator/resources/ec2_linux_test_matrix.json

Cost is increasing in our integration test account. 
EC2 linux now will get 2 vcpu and 4gb ram.  
None

Reduce EC2 Linux Integration Test Cost

---

test/canary/resources/canary_config.json

Canary has no metrics about the agent. 
Add procstat metrics about the agent. 
Manual run the canary test.

Add Basic Canary Config

---

terraform/ec2/README.md

Added missing permissions to mount efs for ec2 linux tests

Add missing efs permissions

---

terraform/ec2/linux/main.tf
terraform/ec2/localstack/main.tf
terraform/ec2/win/main.tf
terraform/ecs_ec2/daemon/main.tf
terraform/performance/main.tf

IMDSv1 will be deprecated. 
Remove calls to imdsv1.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4225783884

Remove IMDSv1 Access

---

.github/workflows/build-check.yml
terraform/ec2/linux/main.tf
terraform/ec2/linux/variables.tf
terraform/ec2/localstack/main.tf
terraform/ec2/win/main.tf
terraform/ecs_ec2/daemon/main.tf
terraform/performance/main.tf
terraform/setup/vpc.tf

Terraform is not formatted 
Add a terraform linter. 
Actions run in gh

Add A Terraform Linter

---

go.mod
go.sum
internal/awsservice/cloudformation.go
internal/awsservice/constant.go
test/cloudformation/cloudformation_test.go
test/cloudformation/resources/AmazonCloudWatchAgent/inline/amazon_linux.template
test/metric/dimension/provider.go
test/metric/metric_validation_util.go
test/metric_value_benchmark/collectd_test.go
test/metric_value_benchmark/container_insights_test.go
test/metric_value_benchmark/cpu_test.go
test/metric_value_benchmark/disk_test.go
test/metric_value_benchmark/diskio_test.go
test/metric_value_benchmark/eks_daemonset_test.go
test/metric_value_benchmark/emf_test.go
test/metric_value_benchmark/ethtool_test.go
test/metric_value_benchmark/mem_test.go
test/metric_value_benchmark/metrics_value_benchmark_test.go
test/metric_value_benchmark/net_test.go
test/metric_value_benchmark/netstat_test.go
test/metric_value_benchmark/processes_test.go
test/metric_value_benchmark/procstat_test.go
test/metric_value_benchmark/prometheus_test.go
test/metric_value_benchmark/statsd_test.go
test/metric_value_benchmark/swap_test.go

We need to migrate cf tests
Add cloudformation test for al
Extra info 
https://github.com/awslabs/aws-cloudformation-templates/pull/383 cf template

Add Cloudformation Test

---

generator/resources/ec2_gpu_test_matrix.json
terraform/ec2/win/main.tf
terraform/ec2/win/variable.tf
terraform/validator/main.tf

This reverts commit adf3a6409b6aae68c541ece54617c725c2239af0.
ssh with password auth is not preferred for windows.
Revert the change
N/A

Revert "Add Nvidia GPU test for Windows (#254)"

---

terraform/ec2/linux/variables.tf

Empty string broke tests.
Sets it to echo.

Set default pre_test_setup to echo.

---

test/metric_value_benchmark/eks_resources/test_schemas/cluster.json
test/metric_value_benchmark/eks_resources/test_schemas/cluster_service.json
test/metric_value_benchmark/eks_resources/test_schemas/container.json
test/metric_value_benchmark/eks_resources/test_schemas/node.json
test/metric_value_benchmark/eks_resources/test_schemas/pod.json

New metrics were added to EKS CI that are now present in the raw EMF logs but are not part of the schema we expect.
Update the expected schema to include the new metrics.
Tested via an integ run on this branch.

Update expected schemas for EKS CI EMF logs

---

test/emf/ecs_resources/ec2_launch/daemon/ecs_taskdef.tpl
test/emf/emf_container_test.go
test/metric/dimension/emf_ecs_dimension_provider.go

Other ECS tests were using the wrong dimension provider, and EMF ECS was using a hardcoded value. 
Fixes issue with ECS tests using different dimension providers, and EMF ECS tests emitting a clustername instead of hardcoded value
Integration tests

Ecs test issue

---

terraform/eks/daemon/emf/main.tf
test/emf/emf_container_test.go

EMF metrics on EKS were not verifying/emitting properly.
Changes to emit metrics by cluster name, and verifies properly.
Integration testing

EMF EKS issue

---

terraform/ecs_ec2/daemon/main.tf

Search asg by tag filter does not work with wildcards
Add a base tag that is not generated
N/A

Add Base Name Tag To ECS ASG For Searching

---

test/metrics_number_dimension/metrics_number_dimension_test.go
test/metrics_number_dimension/resources/10_dimension/config.json
test/metrics_number_dimension/resources/30_dimension/config.json
test/metrics_number_dimension/resources/35_dimension/config.json
util/awsservice/cloudwatchmetrics.go

Flaky test
Add more metrics per minute to reduce the chance of not publishing or indexing in cw
export AWS_REGION=us-west-2
go test -computeType=EC2 -p 1 -v
from within the dir on ec2 instance

Reduce Chance Of Flakiness By Submitting Metrics More Often

---

test/app_signals/resources/config.json
test/app_signals/resources/metrics/server_consumer.json
test/app_signals/traces_test.go
test/metric/app_signals_util.go

Missing integ tests for custom rules
Enhance existing EKS integration test suite with custom rules
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6957463224

Add custom rules test cases to EKS integ test

---

generator/resources/ec2_linux_test_matrix.json
generator/test_case_generator.go

Build itar test matrix for ec2
Build itar test matrix for ec2
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7995989250
Output 
```
[
{
"test_dir": "./test/ca_bundle",
"os": "al2023",
"family": "linux",
"testType": "ec2_linux",
"arc": "arm64",
"instanceType": "m6g.medium",
"ami": "cloudwatch-agent-integration-test-aarch64-al2023*",
"binaryName": "amazon-cloudwatch-agent.rpm",
"username": "ec2-user",
"installAgentCommand": "go run ./install/install_agent.go rpm",
"agentStartCommand": "",
"caCertPath": "/etc/ssl/certs/ca-bundle.crt",
"values_per_minute": 0,
"k8s_version": "",
"terraform_dir": "",
"useSSM": false,
"excludedTests": "", …
```

Add ITAR Tests

---

localstack/ls_tmp/snakeoil.conf

CA bundle test failing in itar
Add itar to conf of snakeoil
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8008808122/job/21878589836

Add *.us-gov-east-1.compute.amazonaws.com To Snakeoil

---

localstack/ls_tmp/snakeoil.conf

* add cn dns
_Describe the problem or feature in addition to a link to the issues._
_How does this change address the problem?_

add cn dns (#391)

---

generator/test_case_generator.go
terraform/eks/daemon/kueue/main.tf
terraform/eks/daemon/kueue/providers.tf
terraform/eks/daemon/kueue/variables.tf
test/kueue/kueue-metrics-test.go
test/kueue/resources/config.json
test/kueue/resources/httpd.conf
test/kueue/resources/metrics_list.go
test/metric/container_insights_util.go
test/metric_value_benchmark/eks_resources/test_schemas/cluster_kueue.json
test/metric_value_benchmark/eks_resources/test_schemas/cluster_kueue_usage.json
test/metric_value_benchmark/eks_resources/util.go

kueue metrics integration tests

---

.github/workflows/build-check.yml

Our build check is currently failing.
Add a step for terraform in our `build-check.yml` file
The checks now pass

Add terraform step to fix the build checks

---

test/fluent/fluent_test.go

There are flaky fluent tests that struggle to properly detect log groups in CloudWatch: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13950271667/job/39047812674.
After investigation, it's apparent that the tests aren't properly checking all log events for expected log messages, doesn't include the `{"log", "az", "ec2_instance_id"}` format for Windows dataplane logs, and isn't retrying with adequate timeouts.
- Check all log events for expected log messages.
- Add `{"log", "az", "ec2_instance_id"}` expected log message format for Windows dataplane log groups.
- Add retry with timeout mechanism.
[View Workflow Run …

Fix flaky fluent tests

---

generator/test_case_generator.go
test/metric_value_benchmark/jmx_kafka_test.go

Currently CWA test suite is blocked by this test to reach 100%. The fix is ongoing and until then this test will be skipped and readded once it is fixed. 

Skipping Efa test 

---

terraform/ec2/assume_role/main.tf
terraform/ec2/common/linux/main.tf
terraform/ec2/creds/main.tf
terraform/ec2/localstack/main.tf
terraform/ec2/mac/main.tf
terraform/ec2/proxy/main.tf
terraform/ec2/userdata/main.tf
terraform/ec2/win/main.tf
terraform/ecs_ec2/daemon/main.tf
terraform/performance/main.tf
terraform/stress/main.tf

Add owners to AMIs.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14478472784

 Add owners to AMIs 
